name: workout_logger_mvp
description: MVP web app para registrar e analisar treinos de musculação.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.5
  provider: ^6.1.2
  table_calendar: ^3.1.1
  file_picker: ^6.1.1
  csv: ^5.0.2
  fl_chart: ^0.66.2
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/samples/
    - .env.example
